version: "3"
services:
 db:
  image: "postgres:latest"
  volumes:
   - postgresdata:/var/lib/postgres/data
  environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
  ports:
   - "5432:5432"
 onlinebank:
  image: "onlinebank:latest"
  stdin_open: true
  volumes:
     - "/home/dell/gowork/src/github.com/sharmamanan796/onlineBank:/go/src/github.com/sharmamanan796/onlineBank"
volumes:
 postgresdata:





  test: bb779de1dda91b633837d10c5993f1c86113f6eb
